// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: chat/chat.proto

package chat

import (
	base_models "github.com/relaunch-cot/lib-relaunch-cot/proto/base_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ////////////////////////////// CREATE NEW CHAT REQUEST
type CreateNewChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,2,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewChatRequest) Reset() {
	*x = CreateNewChatRequest{}
	mi := &file_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewChatRequest) ProtoMessage() {}

func (x *CreateNewChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewChatRequest.ProtoReflect.Descriptor instead.
func (*CreateNewChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewChatRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *CreateNewChatRequest) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

// ////////////////////////////// SEND MESSAGE REQUEST
type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       int64                  `protobuf:"varint,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ChatId         int64                  `protobuf:"varint,2,opt,name=chatId,proto3" json:"chatId,omitempty"`
	MessageContent string                 `protobuf:"bytes,3,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

// ////////////////////////////// GET ALL MESSAGES FROM CHAT REQUEST
type GetAllMessagesFromChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMessagesFromChatRequest) Reset() {
	*x = GetAllMessagesFromChatRequest{}
	mi := &file_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMessagesFromChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMessagesFromChatRequest) ProtoMessage() {}

func (x *GetAllMessagesFromChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMessagesFromChatRequest.ProtoReflect.Descriptor instead.
func (*GetAllMessagesFromChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllMessagesFromChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

// ////////////////////////////// GET ALL MESSAGES FROM CHAT RESPONSE
type GetAllMessagesFromChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*base_models.Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMessagesFromChatResponse) Reset() {
	*x = GetAllMessagesFromChatResponse{}
	mi := &file_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMessagesFromChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMessagesFromChatResponse) ProtoMessage() {}

func (x *GetAllMessagesFromChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMessagesFromChatResponse.ProtoReflect.Descriptor instead.
func (*GetAllMessagesFromChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllMessagesFromChatResponse) GetMessages() []*base_models.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_chat_chat_proto protoreflect.FileDescriptor

const file_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x0fchat/chat.proto\x12\x04chat\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dbase_models/base_models.proto\"N\n" +
	"\x14CreateNewChatRequest\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\x03R\auserIds\x12\x1c\n" +
	"\tcreatedBy\x18\x02 \x01(\x03R\tcreatedBy\"p\n" +
	"\x12SendMessageRequest\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\x03R\bsenderId\x12\x16\n" +
	"\x06chatId\x18\x02 \x01(\x03R\x06chatId\x12&\n" +
	"\x0emessageContent\x18\x03 \x01(\tR\x0emessageContent\"7\n" +
	"\x1dGetAllMessagesFromChatRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\x03R\x06chatId\"R\n" +
	"\x1eGetAllMessagesFromChatResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.base_models.MessageR\bmessages2\xf8\x01\n" +
	"\vChatService\x12C\n" +
	"\rCreateNewChat\x12\x1a.chat.CreateNewChatRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\vSendMessage\x12\x18.chat.SendMessageRequest\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\x16GetAllMessagesFromChat\x12#.chat.GetAllMessagesFromChatRequest\x1a$.chat.GetAllMessagesFromChatResponseB5Z3github.com/relaunch-cot/lib-relaunch-cot/proto/chatb\x06proto3"

var (
	file_chat_chat_proto_rawDescOnce sync.Once
	file_chat_chat_proto_rawDescData []byte
)

func file_chat_chat_proto_rawDescGZIP() []byte {
	file_chat_chat_proto_rawDescOnce.Do(func() {
		file_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)))
	})
	return file_chat_chat_proto_rawDescData
}

var file_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chat_chat_proto_goTypes = []any{
	(*CreateNewChatRequest)(nil),           // 0: chat.CreateNewChatRequest
	(*SendMessageRequest)(nil),             // 1: chat.SendMessageRequest
	(*GetAllMessagesFromChatRequest)(nil),  // 2: chat.GetAllMessagesFromChatRequest
	(*GetAllMessagesFromChatResponse)(nil), // 3: chat.GetAllMessagesFromChatResponse
	(*base_models.Message)(nil),            // 4: base_models.Message
	(*emptypb.Empty)(nil),                  // 5: google.protobuf.Empty
}
var file_chat_chat_proto_depIdxs = []int32{
	4, // 0: chat.GetAllMessagesFromChatResponse.messages:type_name -> base_models.Message
	0, // 1: chat.ChatService.CreateNewChat:input_type -> chat.CreateNewChatRequest
	1, // 2: chat.ChatService.SendMessage:input_type -> chat.SendMessageRequest
	2, // 3: chat.ChatService.GetAllMessagesFromChat:input_type -> chat.GetAllMessagesFromChatRequest
	5, // 4: chat.ChatService.CreateNewChat:output_type -> google.protobuf.Empty
	5, // 5: chat.ChatService.SendMessage:output_type -> google.protobuf.Empty
	3, // 6: chat.ChatService.GetAllMessagesFromChat:output_type -> chat.GetAllMessagesFromChatResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chat_chat_proto_init() }
func file_chat_chat_proto_init() {
	if File_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chat_proto_goTypes,
		DependencyIndexes: file_chat_chat_proto_depIdxs,
		MessageInfos:      file_chat_chat_proto_msgTypes,
	}.Build()
	File_chat_chat_proto = out.File
	file_chat_chat_proto_goTypes = nil
	file_chat_chat_proto_depIdxs = nil
}
