// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: chat/chat.proto

package chat

import (
	base_models "github.com/relaunch-cot/lib-relaunch-cot/proto/base_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ////////////////////////////// CREATE NEW CHAT REQUEST
type CreateNewChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewChatRequest) Reset() {
	*x = CreateNewChatRequest{}
	mi := &file_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewChatRequest) ProtoMessage() {}

func (x *CreateNewChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewChatRequest.ProtoReflect.Descriptor instead.
func (*CreateNewChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewChatRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *CreateNewChatRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// ////////////////////////////// SEND MESSAGE REQUEST
type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ChatId         string                 `protobuf:"bytes,2,opt,name=chatId,proto3" json:"chatId,omitempty"`
	MessageContent string                 `protobuf:"bytes,3,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

// ////////////////////////////// GET ALL MESSAGES FROM CHAT REQUEST
type GetAllMessagesFromChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMessagesFromChatRequest) Reset() {
	*x = GetAllMessagesFromChatRequest{}
	mi := &file_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMessagesFromChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMessagesFromChatRequest) ProtoMessage() {}

func (x *GetAllMessagesFromChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMessagesFromChatRequest.ProtoReflect.Descriptor instead.
func (*GetAllMessagesFromChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllMessagesFromChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// ////////////////////////////// GET ALL MESSAGES FROM CHAT RESPONSE
type GetAllMessagesFromChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*base_models.Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMessagesFromChatResponse) Reset() {
	*x = GetAllMessagesFromChatResponse{}
	mi := &file_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMessagesFromChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMessagesFromChatResponse) ProtoMessage() {}

func (x *GetAllMessagesFromChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMessagesFromChatResponse.ProtoReflect.Descriptor instead.
func (*GetAllMessagesFromChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllMessagesFromChatResponse) GetMessages() []*base_models.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ////////////////////////////// GET ALL CHATS FROM USER REQUEST
type GetAllChatsFromUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllChatsFromUserRequest) Reset() {
	*x = GetAllChatsFromUserRequest{}
	mi := &file_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllChatsFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllChatsFromUserRequest) ProtoMessage() {}

func (x *GetAllChatsFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllChatsFromUserRequest.ProtoReflect.Descriptor instead.
func (*GetAllChatsFromUserRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllChatsFromUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ////////////////////////////// GET ALL CHATS FROM USER RESPONSE
type GetAllChatsFromUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*base_models.Chat    `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllChatsFromUserResponse) Reset() {
	*x = GetAllChatsFromUserResponse{}
	mi := &file_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllChatsFromUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllChatsFromUserResponse) ProtoMessage() {}

func (x *GetAllChatsFromUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllChatsFromUserResponse.ProtoReflect.Descriptor instead.
func (*GetAllChatsFromUserResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllChatsFromUserResponse) GetChats() []*base_models.Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

// ////////////////////////////// GET CHAT FROM USERS REQUEST
type GetChatFromUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatFromUsersRequest) Reset() {
	*x = GetChatFromUsersRequest{}
	mi := &file_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatFromUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatFromUsersRequest) ProtoMessage() {}

func (x *GetChatFromUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatFromUsersRequest.ProtoReflect.Descriptor instead.
func (*GetChatFromUsersRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatFromUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// ////////////////////////////// GET CHAT FROM USERS RESPONSE
type GetChatFromUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *base_models.Chat      `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatFromUsersResponse) Reset() {
	*x = GetChatFromUsersResponse{}
	mi := &file_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatFromUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatFromUsersResponse) ProtoMessage() {}

func (x *GetChatFromUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatFromUsersResponse.ProtoReflect.Descriptor instead.
func (*GetChatFromUsersResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatFromUsersResponse) GetChat() *base_models.Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

// ////////////////////////////// GET CHAT BY ID REQUEST
type GetChatByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatByIdRequest) Reset() {
	*x = GetChatByIdRequest{}
	mi := &file_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByIdRequest) ProtoMessage() {}

func (x *GetChatByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByIdRequest.ProtoReflect.Descriptor instead.
func (*GetChatByIdRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatByIdRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// ////////////////////////////// GET CHAT BY ID RESPONSE
type GetChatByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *base_models.Chat      `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatByIdResponse) Reset() {
	*x = GetChatByIdResponse{}
	mi := &file_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByIdResponse) ProtoMessage() {}

func (x *GetChatByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByIdResponse.ProtoReflect.Descriptor instead.
func (*GetChatByIdResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetChatByIdResponse) GetChat() *base_models.Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

var File_chat_chat_proto protoreflect.FileDescriptor

const file_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x0fchat/chat.proto\x12\x04chat\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dbase_models/base_models.proto\"N\n" +
	"\x14CreateNewChatRequest\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\tR\auserIds\x12\x1c\n" +
	"\tcreatedBy\x18\x02 \x01(\tR\tcreatedBy\"p\n" +
	"\x12SendMessageRequest\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\tR\bsenderId\x12\x16\n" +
	"\x06chatId\x18\x02 \x01(\tR\x06chatId\x12&\n" +
	"\x0emessageContent\x18\x03 \x01(\tR\x0emessageContent\"7\n" +
	"\x1dGetAllMessagesFromChatRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\"R\n" +
	"\x1eGetAllMessagesFromChatResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.base_models.MessageR\bmessages\"4\n" +
	"\x1aGetAllChatsFromUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x1bGetAllChatsFromUserResponse\x12'\n" +
	"\x05chats\x18\x01 \x03(\v2\x11.base_models.ChatR\x05chats\"3\n" +
	"\x17GetChatFromUsersRequest\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\tR\auserIds\"A\n" +
	"\x18GetChatFromUsersResponse\x12%\n" +
	"\x04chat\x18\x01 \x01(\v2\x11.base_models.ChatR\x04chat\",\n" +
	"\x12GetChatByIdRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\"<\n" +
	"\x13GetChatByIdResponse\x12%\n" +
	"\x04chat\x18\x01 \x01(\v2\x11.base_models.ChatR\x04chat2\xeb\x03\n" +
	"\vChatService\x12C\n" +
	"\rCreateNewChat\x12\x1a.chat.CreateNewChatRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\vSendMessage\x12\x18.chat.SendMessageRequest\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\x16GetAllMessagesFromChat\x12#.chat.GetAllMessagesFromChatRequest\x1a$.chat.GetAllMessagesFromChatResponse\x12Z\n" +
	"\x13GetAllChatsFromUser\x12 .chat.GetAllChatsFromUserRequest\x1a!.chat.GetAllChatsFromUserResponse\x12Q\n" +
	"\x10GetChatFromUsers\x12\x1d.chat.GetChatFromUsersRequest\x1a\x1e.chat.GetChatFromUsersResponse\x12B\n" +
	"\vGetChatById\x12\x18.chat.GetChatByIdRequest\x1a\x19.chat.GetChatByIdResponseB5Z3github.com/relaunch-cot/lib-relaunch-cot/proto/chatb\x06proto3"

var (
	file_chat_chat_proto_rawDescOnce sync.Once
	file_chat_chat_proto_rawDescData []byte
)

func file_chat_chat_proto_rawDescGZIP() []byte {
	file_chat_chat_proto_rawDescOnce.Do(func() {
		file_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)))
	})
	return file_chat_chat_proto_rawDescData
}

var file_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chat_chat_proto_goTypes = []any{
	(*CreateNewChatRequest)(nil),           // 0: chat.CreateNewChatRequest
	(*SendMessageRequest)(nil),             // 1: chat.SendMessageRequest
	(*GetAllMessagesFromChatRequest)(nil),  // 2: chat.GetAllMessagesFromChatRequest
	(*GetAllMessagesFromChatResponse)(nil), // 3: chat.GetAllMessagesFromChatResponse
	(*GetAllChatsFromUserRequest)(nil),     // 4: chat.GetAllChatsFromUserRequest
	(*GetAllChatsFromUserResponse)(nil),    // 5: chat.GetAllChatsFromUserResponse
	(*GetChatFromUsersRequest)(nil),        // 6: chat.GetChatFromUsersRequest
	(*GetChatFromUsersResponse)(nil),       // 7: chat.GetChatFromUsersResponse
	(*GetChatByIdRequest)(nil),             // 8: chat.GetChatByIdRequest
	(*GetChatByIdResponse)(nil),            // 9: chat.GetChatByIdResponse
	(*base_models.Message)(nil),            // 10: base_models.Message
	(*base_models.Chat)(nil),               // 11: base_models.Chat
	(*emptypb.Empty)(nil),                  // 12: google.protobuf.Empty
}
var file_chat_chat_proto_depIdxs = []int32{
	10, // 0: chat.GetAllMessagesFromChatResponse.messages:type_name -> base_models.Message
	11, // 1: chat.GetAllChatsFromUserResponse.chats:type_name -> base_models.Chat
	11, // 2: chat.GetChatFromUsersResponse.chat:type_name -> base_models.Chat
	11, // 3: chat.GetChatByIdResponse.chat:type_name -> base_models.Chat
	0,  // 4: chat.ChatService.CreateNewChat:input_type -> chat.CreateNewChatRequest
	1,  // 5: chat.ChatService.SendMessage:input_type -> chat.SendMessageRequest
	2,  // 6: chat.ChatService.GetAllMessagesFromChat:input_type -> chat.GetAllMessagesFromChatRequest
	4,  // 7: chat.ChatService.GetAllChatsFromUser:input_type -> chat.GetAllChatsFromUserRequest
	6,  // 8: chat.ChatService.GetChatFromUsers:input_type -> chat.GetChatFromUsersRequest
	8,  // 9: chat.ChatService.GetChatById:input_type -> chat.GetChatByIdRequest
	12, // 10: chat.ChatService.CreateNewChat:output_type -> google.protobuf.Empty
	12, // 11: chat.ChatService.SendMessage:output_type -> google.protobuf.Empty
	3,  // 12: chat.ChatService.GetAllMessagesFromChat:output_type -> chat.GetAllMessagesFromChatResponse
	5,  // 13: chat.ChatService.GetAllChatsFromUser:output_type -> chat.GetAllChatsFromUserResponse
	7,  // 14: chat.ChatService.GetChatFromUsers:output_type -> chat.GetChatFromUsersResponse
	9,  // 15: chat.ChatService.GetChatById:output_type -> chat.GetChatByIdResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_chat_chat_proto_init() }
func file_chat_chat_proto_init() {
	if File_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chat_proto_goTypes,
		DependencyIndexes: file_chat_chat_proto_depIdxs,
		MessageInfos:      file_chat_chat_proto_msgTypes,
	}.Build()
	File_chat_chat_proto = out.File
	file_chat_chat_proto_goTypes = nil
	file_chat_chat_proto_depIdxs = nil
}
