// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: project/project.proto

package project

import (
	base_models "github.com/relaunch-cot/lib-relaunch-cot/proto/base_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ////////////////////////////// CREATE PROJECT REQUEST
type CreateProjectRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserId                  string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FreelancerId            string                 `protobuf:"bytes,4,opt,name=freelancerId,proto3" json:"freelancerId,omitempty"`
	Name                    string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description             string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Category                string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	ProjectDeliveryDeadline string                 `protobuf:"bytes,8,opt,name=projectDeliveryDeadline,proto3" json:"projectDeliveryDeadline,omitempty"`
	Amount                  float32                `protobuf:"fixed32,9,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProjectRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProjectRequest) GetProjectDeliveryDeadline() string {
	if x != nil {
		return x.ProjectDeliveryDeadline
	}
	return ""
}

func (x *CreateProjectRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// ////////////////////////////// GET PROJECT REQUEST
type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_project_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// ////////////////////////////// GET PROJECT RESPONSE
type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *base_models.Project   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_project_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectResponse) GetProject() *base_models.Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ////////////////////////////// GET ALL PROJECTS FROM USER REQUEST
type GetAllProjectsFromUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProjectsFromUserRequest) Reset() {
	*x = GetAllProjectsFromUserRequest{}
	mi := &file_project_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProjectsFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProjectsFromUserRequest) ProtoMessage() {}

func (x *GetAllProjectsFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProjectsFromUserRequest.ProtoReflect.Descriptor instead.
func (*GetAllProjectsFromUserRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllProjectsFromUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ////////////////////////////// GET ALL PROJECTS FROM USER RESPONSE
type GetAllProjectsFromUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*base_models.Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProjectsFromUserResponse) Reset() {
	*x = GetAllProjectsFromUserResponse{}
	mi := &file_project_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProjectsFromUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProjectsFromUserResponse) ProtoMessage() {}

func (x *GetAllProjectsFromUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProjectsFromUserResponse.ProtoReflect.Descriptor instead.
func (*GetAllProjectsFromUserResponse) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllProjectsFromUserResponse) GetProjects() []*base_models.Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

var File_project_project_proto protoreflect.FileDescriptor

const file_project_project_proto_rawDesc = "" +
	"\n" +
	"\x15project/project.proto\x12\aproject\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dbase_models/base_models.proto\"\xf6\x01\n" +
	"\x14CreateProjectRequest\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\"\n" +
	"\ffreelancerId\x18\x04 \x01(\tR\ffreelancerId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x128\n" +
	"\x17projectDeliveryDeadline\x18\b \x01(\tR\x17projectDeliveryDeadline\x12\x16\n" +
	"\x06amount\x18\t \x01(\x02R\x06amount\"1\n" +
	"\x11GetProjectRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\"D\n" +
	"\x12GetProjectResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.base_models.ProjectR\aproject\"7\n" +
	"\x1dGetAllProjectsFromUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x1eGetAllProjectsFromUserResponse\x120\n" +
	"\bprojects\x18\x01 \x03(\v2\x14.base_models.ProjectR\bprojects2\x8a\x02\n" +
	"\x0eProjectService\x12F\n" +
	"\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\n" +
	"GetProject\x12\x1a.project.GetProjectRequest\x1a\x1b.project.GetProjectResponse\x12i\n" +
	"\x16GetAllProjectsFromUser\x12&.project.GetAllProjectsFromUserRequest\x1a'.project.GetAllProjectsFromUserResponseB8Z6github.com/relaunch-cot/lib-relaunch-cot/proto/projectb\x06proto3"

var (
	file_project_project_proto_rawDescOnce sync.Once
	file_project_project_proto_rawDescData []byte
)

func file_project_project_proto_rawDescGZIP() []byte {
	file_project_project_proto_rawDescOnce.Do(func() {
		file_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)))
	})
	return file_project_project_proto_rawDescData
}

var file_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_project_project_proto_goTypes = []any{
	(*CreateProjectRequest)(nil),           // 0: project.CreateProjectRequest
	(*GetProjectRequest)(nil),              // 1: project.GetProjectRequest
	(*GetProjectResponse)(nil),             // 2: project.GetProjectResponse
	(*GetAllProjectsFromUserRequest)(nil),  // 3: project.GetAllProjectsFromUserRequest
	(*GetAllProjectsFromUserResponse)(nil), // 4: project.GetAllProjectsFromUserResponse
	(*base_models.Project)(nil),            // 5: base_models.Project
	(*emptypb.Empty)(nil),                  // 6: google.protobuf.Empty
}
var file_project_project_proto_depIdxs = []int32{
	5, // 0: project.GetProjectResponse.project:type_name -> base_models.Project
	5, // 1: project.GetAllProjectsFromUserResponse.projects:type_name -> base_models.Project
	0, // 2: project.ProjectService.CreateProject:input_type -> project.CreateProjectRequest
	1, // 3: project.ProjectService.GetProject:input_type -> project.GetProjectRequest
	3, // 4: project.ProjectService.GetAllProjectsFromUser:input_type -> project.GetAllProjectsFromUserRequest
	6, // 5: project.ProjectService.CreateProject:output_type -> google.protobuf.Empty
	2, // 6: project.ProjectService.GetProject:output_type -> project.GetProjectResponse
	4, // 7: project.ProjectService.GetAllProjectsFromUser:output_type -> project.GetAllProjectsFromUserResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_project_project_proto_init() }
func file_project_project_proto_init() {
	if File_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_project_proto_goTypes,
		DependencyIndexes: file_project_project_proto_depIdxs,
		MessageInfos:      file_project_project_proto_msgTypes,
	}.Build()
	File_project_project_proto = out.File
	file_project_project_proto_goTypes = nil
	file_project_project_proto_depIdxs = nil
}
