// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: post/post.proto

package post

import (
	base_models "github.com/relaunch-cot/lib-relaunch-cot/proto/base_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// //////////////////////////// CREATE POST REQUEST
type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	UrlImagePost  string                 `protobuf:"bytes,5,opt,name=urlImagePost,proto3" json:"urlImagePost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_post_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePostRequest) GetUrlImagePost() string {
	if x != nil {
		return x.UrlImagePost
	}
	return ""
}

// //////////////////////////// GET POST REQUEST
type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_post_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// //////////////////////////// GET POST RESPONSE
type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *base_models.Post      `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_post_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostResponse) GetPost() *base_models.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

// //////////////////////////// GET ALL POSTS FROM USER REQUEST
type GetAllPostsFromUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsFromUserRequest) Reset() {
	*x = GetAllPostsFromUserRequest{}
	mi := &file_post_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsFromUserRequest) ProtoMessage() {}

func (x *GetAllPostsFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsFromUserRequest.ProtoReflect.Descriptor instead.
func (*GetAllPostsFromUserRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllPostsFromUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// //////////////////////////// GET ALL POSTS FROM USER RESPONSE
type GetAllPostsFromUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*base_models.Post    `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsFromUserResponse) Reset() {
	*x = GetAllPostsFromUserResponse{}
	mi := &file_post_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsFromUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsFromUserResponse) ProtoMessage() {}

func (x *GetAllPostsFromUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsFromUserResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsFromUserResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllPostsFromUserResponse) GetPosts() []*base_models.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

// //////////////////////////// UPDATE POST REQUEST
type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	UrlImagePost  string                 `protobuf:"bytes,5,opt,name=urlImagePost,proto3" json:"urlImagePost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_post_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostRequest) GetUrlImagePost() string {
	if x != nil {
		return x.UrlImagePost
	}
	return ""
}

// //////////////////////////// UPDATE POST RESPONSE
type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *base_models.Post      `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_post_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePostResponse) GetPost() *base_models.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

// //////////////////////////// DELETE POST REQUEST
type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_post_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// //////////////////////////// GET ALL POSTS RESPONSE
type GetAllPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*base_models.Post    `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsResponse) Reset() {
	*x = GetAllPostsResponse{}
	mi := &file_post_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsResponse) ProtoMessage() {}

func (x *GetAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllPostsResponse) GetPosts() []*base_models.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

// //////////////////////////// UPDATE LIKES FROM POST OR COMMENT REQUEST
type UpdateLikesFromPostOrCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	CommentId     string                 `protobuf:"bytes,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLikesFromPostOrCommentRequest) Reset() {
	*x = UpdateLikesFromPostOrCommentRequest{}
	mi := &file_post_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLikesFromPostOrCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLikesFromPostOrCommentRequest) ProtoMessage() {}

func (x *UpdateLikesFromPostOrCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLikesFromPostOrCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateLikesFromPostOrCommentRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLikesFromPostOrCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdateLikesFromPostOrCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UpdateLikesFromPostOrCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLikesFromPostOrCommentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// //////////////////////////// UPDATE LIKES FROM POST OR COMMENT RESPONSE
type UpdateLikesFromPostOrCommentResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LikesFromPostOrComment *base_models.PostLikes `protobuf:"bytes,1,opt,name=likesFromPostOrComment,proto3" json:"likesFromPostOrComment,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateLikesFromPostOrCommentResponse) Reset() {
	*x = UpdateLikesFromPostOrCommentResponse{}
	mi := &file_post_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLikesFromPostOrCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLikesFromPostOrCommentResponse) ProtoMessage() {}

func (x *UpdateLikesFromPostOrCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLikesFromPostOrCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateLikesFromPostOrCommentResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLikesFromPostOrCommentResponse) GetLikesFromPostOrComment() *base_models.PostLikes {
	if x != nil {
		return x.LikesFromPostOrComment
	}
	return nil
}

// //////////////////////////// GET ALL LIKES FROM POST REQUEST
type GetAllLikesFromPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLikesFromPostRequest) Reset() {
	*x = GetAllLikesFromPostRequest{}
	mi := &file_post_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLikesFromPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLikesFromPostRequest) ProtoMessage() {}

func (x *GetAllLikesFromPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLikesFromPostRequest.ProtoReflect.Descriptor instead.
func (*GetAllLikesFromPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllLikesFromPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetAllLikesFromPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// //////////////////////////// GET ALL LIKES FROM POST RESPONSE
type GetAllLikesFromPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikesFromPost *base_models.PostLikes `protobuf:"bytes,1,opt,name=likesFromPost,proto3" json:"likesFromPost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLikesFromPostResponse) Reset() {
	*x = GetAllLikesFromPostResponse{}
	mi := &file_post_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLikesFromPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLikesFromPostResponse) ProtoMessage() {}

func (x *GetAllLikesFromPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLikesFromPostResponse.ProtoReflect.Descriptor instead.
func (*GetAllLikesFromPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllLikesFromPostResponse) GetLikesFromPost() *base_models.PostLikes {
	if x != nil {
		return x.LikesFromPost
	}
	return nil
}

// //////////////////////////// CREATE COMMENT OR REPLY REQUEST
type CreateCommentOrReplyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PostId          string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ParentCommentId string                 `protobuf:"bytes,5,opt,name=parentCommentId,proto3" json:"parentCommentId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCommentOrReplyRequest) Reset() {
	*x = CreateCommentOrReplyRequest{}
	mi := &file_post_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentOrReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentOrReplyRequest) ProtoMessage() {}

func (x *CreateCommentOrReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentOrReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentOrReplyRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCommentOrReplyRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentOrReplyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommentOrReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentOrReplyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateCommentOrReplyRequest) GetParentCommentId() string {
	if x != nil {
		return x.ParentCommentId
	}
	return ""
}

// //////////////////////////// CREATE COMMENT OR REPLY TO POST RESPONSE
type CreateCommentOrReplyResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	CommentsFromPost *base_models.PostComments `protobuf:"bytes,1,opt,name=commentsFromPost,proto3" json:"commentsFromPost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCommentOrReplyResponse) Reset() {
	*x = CreateCommentOrReplyResponse{}
	mi := &file_post_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentOrReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentOrReplyResponse) ProtoMessage() {}

func (x *CreateCommentOrReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentOrReplyResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentOrReplyResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCommentOrReplyResponse) GetCommentsFromPost() *base_models.PostComments {
	if x != nil {
		return x.CommentsFromPost
	}
	return nil
}

// //////////////////////////// DELETE COMMENT OR REPLY REQUEST
type DeleteCommentOrReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     string                 `protobuf:"bytes,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	ReplyId       string                 `protobuf:"bytes,3,opt,name=replyId,proto3" json:"replyId,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentOrReplyRequest) Reset() {
	*x = DeleteCommentOrReplyRequest{}
	mi := &file_post_post_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentOrReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentOrReplyRequest) ProtoMessage() {}

func (x *DeleteCommentOrReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentOrReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentOrReplyRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCommentOrReplyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteCommentOrReplyRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DeleteCommentOrReplyRequest) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *DeleteCommentOrReplyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// //////////////////////////// REMOVE COMMENT OR REPLY RESPONSE
type DeleteCommentOrReplyResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	CommentsFromPost *base_models.PostComments `protobuf:"bytes,1,opt,name=commentsFromPost,proto3" json:"commentsFromPost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteCommentOrReplyResponse) Reset() {
	*x = DeleteCommentOrReplyResponse{}
	mi := &file_post_post_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentOrReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentOrReplyResponse) ProtoMessage() {}

func (x *DeleteCommentOrReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentOrReplyResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentOrReplyResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCommentOrReplyResponse) GetCommentsFromPost() *base_models.PostComments {
	if x != nil {
		return x.CommentsFromPost
	}
	return nil
}

// //////////////////////////// GET ALL COMMENTS FROM POST REQUEST
type GetAllCommentsFromPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCommentsFromPostRequest) Reset() {
	*x = GetAllCommentsFromPostRequest{}
	mi := &file_post_post_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommentsFromPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommentsFromPostRequest) ProtoMessage() {}

func (x *GetAllCommentsFromPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommentsFromPostRequest.ProtoReflect.Descriptor instead.
func (*GetAllCommentsFromPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllCommentsFromPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetAllCommentsFromPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// //////////////////////////// GET ALL COMMENTS FROM POST RESPONSE
type GetAllCommentsFromPostResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	CommentsFromPost *base_models.PostComments `protobuf:"bytes,1,opt,name=commentsFromPost,proto3" json:"commentsFromPost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAllCommentsFromPostResponse) Reset() {
	*x = GetAllCommentsFromPostResponse{}
	mi := &file_post_post_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommentsFromPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommentsFromPostResponse) ProtoMessage() {}

func (x *GetAllCommentsFromPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommentsFromPostResponse.ProtoReflect.Descriptor instead.
func (*GetAllCommentsFromPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllCommentsFromPostResponse) GetCommentsFromPost() *base_models.PostComments {
	if x != nil {
		return x.CommentsFromPost
	}
	return nil
}

var File_post_post_proto protoreflect.FileDescriptor

const file_post_post_proto_rawDesc = "" +
	"\n" +
	"\x0fpost/post.proto\x12\x04post\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dbase_models/base_models.proto\"\x93\x01\n" +
	"\x11CreatePostRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\"\n" +
	"\furlImagePost\x18\x05 \x01(\tR\furlImagePost\"(\n" +
	"\x0eGetPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\"8\n" +
	"\x0fGetPostResponse\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.base_models.PostR\x04post\"4\n" +
	"\x1aGetAllPostsFromUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x1bGetAllPostsFromUserResponse\x12'\n" +
	"\x05posts\x18\x01 \x03(\v2\x11.base_models.PostR\x05posts\"\x97\x01\n" +
	"\x11UpdatePostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\"\n" +
	"\furlImagePost\x18\x05 \x01(\tR\furlImagePost\";\n" +
	"\x12UpdatePostResponse\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.base_models.PostR\x04post\"C\n" +
	"\x11DeletePostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\">\n" +
	"\x13GetAllPostsResponse\x12'\n" +
	"\x05posts\x18\x01 \x03(\v2\x11.base_models.PostR\x05posts\"\x87\x01\n" +
	"#UpdateLikesFromPostOrCommentRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\tR\tcommentId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"v\n" +
	"$UpdateLikesFromPostOrCommentResponse\x12N\n" +
	"\x16likesFromPostOrComment\x18\x01 \x01(\v2\x16.base_models.PostLikesR\x16likesFromPostOrComment\"L\n" +
	"\x1aGetAllLikesFromPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"[\n" +
	"\x1bGetAllLikesFromPostResponse\x12<\n" +
	"\rlikesFromPost\x18\x01 \x01(\v2\x16.base_models.PostLikesR\rlikesFromPost\"\xa5\x01\n" +
	"\x1bCreateCommentOrReplyRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12(\n" +
	"\x0fparentCommentId\x18\x05 \x01(\tR\x0fparentCommentId\"e\n" +
	"\x1cCreateCommentOrReplyResponse\x12E\n" +
	"\x10commentsFromPost\x18\x01 \x01(\v2\x19.base_models.PostCommentsR\x10commentsFromPost\"\x81\x01\n" +
	"\x1bDeleteCommentOrReplyRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\tR\tcommentId\x12\x18\n" +
	"\areplyId\x18\x03 \x01(\tR\areplyId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"e\n" +
	"\x1cDeleteCommentOrReplyResponse\x12E\n" +
	"\x10commentsFromPost\x18\x01 \x01(\v2\x19.base_models.PostCommentsR\x10commentsFromPost\"O\n" +
	"\x1dGetAllCommentsFromPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"g\n" +
	"\x1eGetAllCommentsFromPostResponse\x12E\n" +
	"\x10commentsFromPost\x18\x01 \x01(\v2\x19.base_models.PostCommentsR\x10commentsFromPost2\x98\a\n" +
	"\vPostService\x12=\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\aGetPost\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponse\x12Z\n" +
	"\x13GetAllPostsFromUser\x12 .post.GetAllPostsFromUserRequest\x1a!.post.GetAllPostsFromUserResponse\x12?\n" +
	"\n" +
	"UpdatePost\x12\x17.post.UpdatePostRequest\x1a\x18.post.UpdatePostResponse\x12=\n" +
	"\n" +
	"DeletePost\x12\x17.post.DeletePostRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\vGetAllPosts\x12\x16.google.protobuf.Empty\x1a\x19.post.GetAllPostsResponse\x12u\n" +
	"\x1cUpdateLikesFromPostOrComment\x12).post.UpdateLikesFromPostOrCommentRequest\x1a*.post.UpdateLikesFromPostOrCommentResponse\x12Z\n" +
	"\x13GetAllLikesFromPost\x12 .post.GetAllLikesFromPostRequest\x1a!.post.GetAllLikesFromPostResponse\x12]\n" +
	"\x14CreateCommentOrReply\x12!.post.CreateCommentOrReplyRequest\x1a\".post.CreateCommentOrReplyResponse\x12]\n" +
	"\x14DeleteCommentOrReply\x12!.post.DeleteCommentOrReplyRequest\x1a\".post.DeleteCommentOrReplyResponse\x12c\n" +
	"\x16GetAllCommentsFromPost\x12#.post.GetAllCommentsFromPostRequest\x1a$.post.GetAllCommentsFromPostResponseB5Z3github.com/relaunch-cot/lib-relaunch-cot/proto/postb\x06proto3"

var (
	file_post_post_proto_rawDescOnce sync.Once
	file_post_post_proto_rawDescData []byte
)

func file_post_post_proto_rawDescGZIP() []byte {
	file_post_post_proto_rawDescOnce.Do(func() {
		file_post_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_post_proto_rawDesc), len(file_post_post_proto_rawDesc)))
	})
	return file_post_post_proto_rawDescData
}

var file_post_post_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_post_post_proto_goTypes = []any{
	(*CreatePostRequest)(nil),                    // 0: post.CreatePostRequest
	(*GetPostRequest)(nil),                       // 1: post.GetPostRequest
	(*GetPostResponse)(nil),                      // 2: post.GetPostResponse
	(*GetAllPostsFromUserRequest)(nil),           // 3: post.GetAllPostsFromUserRequest
	(*GetAllPostsFromUserResponse)(nil),          // 4: post.GetAllPostsFromUserResponse
	(*UpdatePostRequest)(nil),                    // 5: post.UpdatePostRequest
	(*UpdatePostResponse)(nil),                   // 6: post.UpdatePostResponse
	(*DeletePostRequest)(nil),                    // 7: post.DeletePostRequest
	(*GetAllPostsResponse)(nil),                  // 8: post.GetAllPostsResponse
	(*UpdateLikesFromPostOrCommentRequest)(nil),  // 9: post.UpdateLikesFromPostOrCommentRequest
	(*UpdateLikesFromPostOrCommentResponse)(nil), // 10: post.UpdateLikesFromPostOrCommentResponse
	(*GetAllLikesFromPostRequest)(nil),           // 11: post.GetAllLikesFromPostRequest
	(*GetAllLikesFromPostResponse)(nil),          // 12: post.GetAllLikesFromPostResponse
	(*CreateCommentOrReplyRequest)(nil),          // 13: post.CreateCommentOrReplyRequest
	(*CreateCommentOrReplyResponse)(nil),         // 14: post.CreateCommentOrReplyResponse
	(*DeleteCommentOrReplyRequest)(nil),          // 15: post.DeleteCommentOrReplyRequest
	(*DeleteCommentOrReplyResponse)(nil),         // 16: post.DeleteCommentOrReplyResponse
	(*GetAllCommentsFromPostRequest)(nil),        // 17: post.GetAllCommentsFromPostRequest
	(*GetAllCommentsFromPostResponse)(nil),       // 18: post.GetAllCommentsFromPostResponse
	(*base_models.Post)(nil),                     // 19: base_models.Post
	(*base_models.PostLikes)(nil),                // 20: base_models.PostLikes
	(*base_models.PostComments)(nil),             // 21: base_models.PostComments
	(*emptypb.Empty)(nil),                        // 22: google.protobuf.Empty
}
var file_post_post_proto_depIdxs = []int32{
	19, // 0: post.GetPostResponse.post:type_name -> base_models.Post
	19, // 1: post.GetAllPostsFromUserResponse.posts:type_name -> base_models.Post
	19, // 2: post.UpdatePostResponse.post:type_name -> base_models.Post
	19, // 3: post.GetAllPostsResponse.posts:type_name -> base_models.Post
	20, // 4: post.UpdateLikesFromPostOrCommentResponse.likesFromPostOrComment:type_name -> base_models.PostLikes
	20, // 5: post.GetAllLikesFromPostResponse.likesFromPost:type_name -> base_models.PostLikes
	21, // 6: post.CreateCommentOrReplyResponse.commentsFromPost:type_name -> base_models.PostComments
	21, // 7: post.DeleteCommentOrReplyResponse.commentsFromPost:type_name -> base_models.PostComments
	21, // 8: post.GetAllCommentsFromPostResponse.commentsFromPost:type_name -> base_models.PostComments
	0,  // 9: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	1,  // 10: post.PostService.GetPost:input_type -> post.GetPostRequest
	3,  // 11: post.PostService.GetAllPostsFromUser:input_type -> post.GetAllPostsFromUserRequest
	5,  // 12: post.PostService.UpdatePost:input_type -> post.UpdatePostRequest
	7,  // 13: post.PostService.DeletePost:input_type -> post.DeletePostRequest
	22, // 14: post.PostService.GetAllPosts:input_type -> google.protobuf.Empty
	9,  // 15: post.PostService.UpdateLikesFromPostOrComment:input_type -> post.UpdateLikesFromPostOrCommentRequest
	11, // 16: post.PostService.GetAllLikesFromPost:input_type -> post.GetAllLikesFromPostRequest
	13, // 17: post.PostService.CreateCommentOrReply:input_type -> post.CreateCommentOrReplyRequest
	15, // 18: post.PostService.DeleteCommentOrReply:input_type -> post.DeleteCommentOrReplyRequest
	17, // 19: post.PostService.GetAllCommentsFromPost:input_type -> post.GetAllCommentsFromPostRequest
	22, // 20: post.PostService.CreatePost:output_type -> google.protobuf.Empty
	2,  // 21: post.PostService.GetPost:output_type -> post.GetPostResponse
	4,  // 22: post.PostService.GetAllPostsFromUser:output_type -> post.GetAllPostsFromUserResponse
	6,  // 23: post.PostService.UpdatePost:output_type -> post.UpdatePostResponse
	22, // 24: post.PostService.DeletePost:output_type -> google.protobuf.Empty
	8,  // 25: post.PostService.GetAllPosts:output_type -> post.GetAllPostsResponse
	10, // 26: post.PostService.UpdateLikesFromPostOrComment:output_type -> post.UpdateLikesFromPostOrCommentResponse
	12, // 27: post.PostService.GetAllLikesFromPost:output_type -> post.GetAllLikesFromPostResponse
	14, // 28: post.PostService.CreateCommentOrReply:output_type -> post.CreateCommentOrReplyResponse
	16, // 29: post.PostService.DeleteCommentOrReply:output_type -> post.DeleteCommentOrReplyResponse
	18, // 30: post.PostService.GetAllCommentsFromPost:output_type -> post.GetAllCommentsFromPostResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_post_post_proto_init() }
func file_post_post_proto_init() {
	if File_post_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_post_proto_rawDesc), len(file_post_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_post_proto_goTypes,
		DependencyIndexes: file_post_post_proto_depIdxs,
		MessageInfos:      file_post_post_proto_msgTypes,
	}.Build()
	File_post_post_proto = out.File
	file_post_post_proto_goTypes = nil
	file_post_post_proto_depIdxs = nil
}
