// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: post/post.proto

package post

import (
	base_models "github.com/relaunch-cot/lib-relaunch-cot/proto/base_models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// //////////////////////////// CREATE POST REQUEST
type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	UrlImagePost  string                 `protobuf:"bytes,5,opt,name=urlImagePost,proto3" json:"urlImagePost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_post_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePostRequest) GetUrlImagePost() string {
	if x != nil {
		return x.UrlImagePost
	}
	return ""
}

// //////////////////////////// GET POST REQUEST
type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_post_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

// //////////////////////////// GET POST RESPONSE
type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *base_models.Post      `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_post_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostResponse) GetPost() *base_models.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

// //////////////////////////// GET ALL POSTS FROM USER REQUEST
type GetAllPostsFromUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsFromUserRequest) Reset() {
	*x = GetAllPostsFromUserRequest{}
	mi := &file_post_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsFromUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsFromUserRequest) ProtoMessage() {}

func (x *GetAllPostsFromUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsFromUserRequest.ProtoReflect.Descriptor instead.
func (*GetAllPostsFromUserRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllPostsFromUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// //////////////////////////// GET ALL POSTS FROM USER RESPONSE
type GetAllPostsFromUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*base_models.Post    `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsFromUserResponse) Reset() {
	*x = GetAllPostsFromUserResponse{}
	mi := &file_post_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsFromUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsFromUserResponse) ProtoMessage() {}

func (x *GetAllPostsFromUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsFromUserResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsFromUserResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllPostsFromUserResponse) GetPosts() []*base_models.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

// //////////////////////////// UPDATE POST REQUEST
type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	UrlImagePost  string                 `protobuf:"bytes,5,opt,name=urlImagePost,proto3" json:"urlImagePost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_post_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostRequest) GetUrlImagePost() string {
	if x != nil {
		return x.UrlImagePost
	}
	return ""
}

// //////////////////////////// UPDATE POST RESPONSE
type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *base_models.Post      `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_post_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePostResponse) GetPost() *base_models.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

// //////////////////////////// DELETE POST REQUEST
type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_post_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// //////////////////////////// GET ALL POSTS RESPONSE
type GetAllPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*base_models.Post    `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPostsResponse) Reset() {
	*x = GetAllPostsResponse{}
	mi := &file_post_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPostsResponse) ProtoMessage() {}

func (x *GetAllPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPostsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPostsResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllPostsResponse) GetPosts() []*base_models.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

// //////////////////////////// UPDATE LIKES FROM POST REQUEST
type UpdateLikesFromPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLikesFromPostRequest) Reset() {
	*x = UpdateLikesFromPostRequest{}
	mi := &file_post_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLikesFromPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLikesFromPostRequest) ProtoMessage() {}

func (x *UpdateLikesFromPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLikesFromPostRequest.ProtoReflect.Descriptor instead.
func (*UpdateLikesFromPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLikesFromPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdateLikesFromPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// //////////////////////////// UPDATE LIKES FROM POST RESPONSE
type UpdateLikesFromPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikesFromPost *base_models.PostLikes `protobuf:"bytes,1,opt,name=likesFromPost,proto3" json:"likesFromPost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLikesFromPostResponse) Reset() {
	*x = UpdateLikesFromPostResponse{}
	mi := &file_post_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLikesFromPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLikesFromPostResponse) ProtoMessage() {}

func (x *UpdateLikesFromPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLikesFromPostResponse.ProtoReflect.Descriptor instead.
func (*UpdateLikesFromPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLikesFromPostResponse) GetLikesFromPost() *base_models.PostLikes {
	if x != nil {
		return x.LikesFromPost
	}
	return nil
}

type AddCommentToPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentToPostRequest) Reset() {
	*x = AddCommentToPostRequest{}
	mi := &file_post_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentToPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentToPostRequest) ProtoMessage() {}

func (x *AddCommentToPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentToPostRequest.ProtoReflect.Descriptor instead.
func (*AddCommentToPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{11}
}

func (x *AddCommentToPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *AddCommentToPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCommentToPostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddCommentToPostResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	CommentsFromPost *base_models.PostComments `protobuf:"bytes,1,opt,name=commentsFromPost,proto3" json:"commentsFromPost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddCommentToPostResponse) Reset() {
	*x = AddCommentToPostResponse{}
	mi := &file_post_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentToPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentToPostResponse) ProtoMessage() {}

func (x *AddCommentToPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentToPostResponse.ProtoReflect.Descriptor instead.
func (*AddCommentToPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{12}
}

func (x *AddCommentToPostResponse) GetCommentsFromPost() *base_models.PostComments {
	if x != nil {
		return x.CommentsFromPost
	}
	return nil
}

type RemoveCommentFromPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     string                 `protobuf:"bytes,3,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommentFromPostRequest) Reset() {
	*x = RemoveCommentFromPostRequest{}
	mi := &file_post_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommentFromPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommentFromPostRequest) ProtoMessage() {}

func (x *RemoveCommentFromPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommentFromPostRequest.ProtoReflect.Descriptor instead.
func (*RemoveCommentFromPostRequest) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveCommentFromPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *RemoveCommentFromPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveCommentFromPostRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type RemoveCommentFromPostResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	CommentsFromPost *base_models.PostComments `protobuf:"bytes,1,opt,name=commentsFromPost,proto3" json:"commentsFromPost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveCommentFromPostResponse) Reset() {
	*x = RemoveCommentFromPostResponse{}
	mi := &file_post_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommentFromPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommentFromPostResponse) ProtoMessage() {}

func (x *RemoveCommentFromPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommentFromPostResponse.ProtoReflect.Descriptor instead.
func (*RemoveCommentFromPostResponse) Descriptor() ([]byte, []int) {
	return file_post_post_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveCommentFromPostResponse) GetCommentsFromPost() *base_models.PostComments {
	if x != nil {
		return x.CommentsFromPost
	}
	return nil
}

var File_post_post_proto protoreflect.FileDescriptor

const file_post_post_proto_rawDesc = "" +
	"\n" +
	"\x0fpost/post.proto\x12\x04post\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dbase_models/base_models.proto\"\x93\x01\n" +
	"\x11CreatePostRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\"\n" +
	"\furlImagePost\x18\x05 \x01(\tR\furlImagePost\"(\n" +
	"\x0eGetPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\"8\n" +
	"\x0fGetPostResponse\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.base_models.PostR\x04post\"4\n" +
	"\x1aGetAllPostsFromUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x1bGetAllPostsFromUserResponse\x12'\n" +
	"\x05posts\x18\x01 \x03(\v2\x11.base_models.PostR\x05posts\"\x97\x01\n" +
	"\x11UpdatePostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\"\n" +
	"\furlImagePost\x18\x05 \x01(\tR\furlImagePost\";\n" +
	"\x12UpdatePostResponse\x12%\n" +
	"\x04post\x18\x01 \x01(\v2\x11.base_models.PostR\x04post\"C\n" +
	"\x11DeletePostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\">\n" +
	"\x13GetAllPostsResponse\x12'\n" +
	"\x05posts\x18\x01 \x03(\v2\x11.base_models.PostR\x05posts\"L\n" +
	"\x1aUpdateLikesFromPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"[\n" +
	"\x1bUpdateLikesFromPostResponse\x12<\n" +
	"\rlikesFromPost\x18\x01 \x01(\v2\x16.base_models.PostLikesR\rlikesFromPost\"c\n" +
	"\x17AddCommentToPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"a\n" +
	"\x18AddCommentToPostResponse\x12E\n" +
	"\x10commentsFromPost\x18\x01 \x01(\v2\x19.base_models.PostCommentsR\x10commentsFromPost\"l\n" +
	"\x1cRemoveCommentFromPostRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x03 \x01(\tR\tcommentId\"f\n" +
	"\x1dRemoveCommentFromPostResponse\x12E\n" +
	"\x10commentsFromPost\x18\x01 \x01(\v2\x19.base_models.PostCommentsR\x10commentsFromPost2\xb3\x05\n" +
	"\vPostService\x12=\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\aGetPost\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponse\x12Z\n" +
	"\x13GetAllPostsFromUser\x12 .post.GetAllPostsFromUserRequest\x1a!.post.GetAllPostsFromUserResponse\x12?\n" +
	"\n" +
	"UpdatePost\x12\x17.post.UpdatePostRequest\x1a\x18.post.UpdatePostResponse\x12=\n" +
	"\n" +
	"DeletePost\x12\x17.post.DeletePostRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\vGetAllPosts\x12\x16.google.protobuf.Empty\x1a\x19.post.GetAllPostsResponse\x12Z\n" +
	"\x13UpdateLikesFromPost\x12 .post.UpdateLikesFromPostRequest\x1a!.post.UpdateLikesFromPostResponse\x12Q\n" +
	"\x10AddCommentToPost\x12\x1d.post.AddCommentToPostRequest\x1a\x1e.post.AddCommentToPostResponse\x12`\n" +
	"\x15RemoveCommentFromPost\x12\".post.RemoveCommentFromPostRequest\x1a#.post.RemoveCommentFromPostResponseB5Z3github.com/relaunch-cot/lib-relaunch-cot/proto/postb\x06proto3"

var (
	file_post_post_proto_rawDescOnce sync.Once
	file_post_post_proto_rawDescData []byte
)

func file_post_post_proto_rawDescGZIP() []byte {
	file_post_post_proto_rawDescOnce.Do(func() {
		file_post_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_post_proto_rawDesc), len(file_post_post_proto_rawDesc)))
	})
	return file_post_post_proto_rawDescData
}

var file_post_post_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_post_post_proto_goTypes = []any{
	(*CreatePostRequest)(nil),             // 0: post.CreatePostRequest
	(*GetPostRequest)(nil),                // 1: post.GetPostRequest
	(*GetPostResponse)(nil),               // 2: post.GetPostResponse
	(*GetAllPostsFromUserRequest)(nil),    // 3: post.GetAllPostsFromUserRequest
	(*GetAllPostsFromUserResponse)(nil),   // 4: post.GetAllPostsFromUserResponse
	(*UpdatePostRequest)(nil),             // 5: post.UpdatePostRequest
	(*UpdatePostResponse)(nil),            // 6: post.UpdatePostResponse
	(*DeletePostRequest)(nil),             // 7: post.DeletePostRequest
	(*GetAllPostsResponse)(nil),           // 8: post.GetAllPostsResponse
	(*UpdateLikesFromPostRequest)(nil),    // 9: post.UpdateLikesFromPostRequest
	(*UpdateLikesFromPostResponse)(nil),   // 10: post.UpdateLikesFromPostResponse
	(*AddCommentToPostRequest)(nil),       // 11: post.AddCommentToPostRequest
	(*AddCommentToPostResponse)(nil),      // 12: post.AddCommentToPostResponse
	(*RemoveCommentFromPostRequest)(nil),  // 13: post.RemoveCommentFromPostRequest
	(*RemoveCommentFromPostResponse)(nil), // 14: post.RemoveCommentFromPostResponse
	(*base_models.Post)(nil),              // 15: base_models.Post
	(*base_models.PostLikes)(nil),         // 16: base_models.PostLikes
	(*base_models.PostComments)(nil),      // 17: base_models.PostComments
	(*emptypb.Empty)(nil),                 // 18: google.protobuf.Empty
}
var file_post_post_proto_depIdxs = []int32{
	15, // 0: post.GetPostResponse.post:type_name -> base_models.Post
	15, // 1: post.GetAllPostsFromUserResponse.posts:type_name -> base_models.Post
	15, // 2: post.UpdatePostResponse.post:type_name -> base_models.Post
	15, // 3: post.GetAllPostsResponse.posts:type_name -> base_models.Post
	16, // 4: post.UpdateLikesFromPostResponse.likesFromPost:type_name -> base_models.PostLikes
	17, // 5: post.AddCommentToPostResponse.commentsFromPost:type_name -> base_models.PostComments
	17, // 6: post.RemoveCommentFromPostResponse.commentsFromPost:type_name -> base_models.PostComments
	0,  // 7: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	1,  // 8: post.PostService.GetPost:input_type -> post.GetPostRequest
	3,  // 9: post.PostService.GetAllPostsFromUser:input_type -> post.GetAllPostsFromUserRequest
	5,  // 10: post.PostService.UpdatePost:input_type -> post.UpdatePostRequest
	7,  // 11: post.PostService.DeletePost:input_type -> post.DeletePostRequest
	18, // 12: post.PostService.GetAllPosts:input_type -> google.protobuf.Empty
	9,  // 13: post.PostService.UpdateLikesFromPost:input_type -> post.UpdateLikesFromPostRequest
	11, // 14: post.PostService.AddCommentToPost:input_type -> post.AddCommentToPostRequest
	13, // 15: post.PostService.RemoveCommentFromPost:input_type -> post.RemoveCommentFromPostRequest
	18, // 16: post.PostService.CreatePost:output_type -> google.protobuf.Empty
	2,  // 17: post.PostService.GetPost:output_type -> post.GetPostResponse
	4,  // 18: post.PostService.GetAllPostsFromUser:output_type -> post.GetAllPostsFromUserResponse
	6,  // 19: post.PostService.UpdatePost:output_type -> post.UpdatePostResponse
	18, // 20: post.PostService.DeletePost:output_type -> google.protobuf.Empty
	8,  // 21: post.PostService.GetAllPosts:output_type -> post.GetAllPostsResponse
	10, // 22: post.PostService.UpdateLikesFromPost:output_type -> post.UpdateLikesFromPostResponse
	12, // 23: post.PostService.AddCommentToPost:output_type -> post.AddCommentToPostResponse
	14, // 24: post.PostService.RemoveCommentFromPost:output_type -> post.RemoveCommentFromPostResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_post_post_proto_init() }
func file_post_post_proto_init() {
	if File_post_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_post_proto_rawDesc), len(file_post_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_post_proto_goTypes,
		DependencyIndexes: file_post_post_proto_depIdxs,
		MessageInfos:      file_post_post_proto_msgTypes,
	}.Build()
	File_post_post_proto = out.File
	file_post_post_proto_goTypes = nil
	file_post_post_proto_depIdxs = nil
}
