// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: base_models/base_models.proto

package base_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Settings      *UserSettings          `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_base_models_base_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_base_models_base_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_base_models_base_models_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Cpf           string                 `protobuf:"bytes,2,opt,name=cpf,proto3" json:"cpf,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	Biography     string                 `protobuf:"bytes,4,opt,name=biography,proto3" json:"biography,omitempty"`
	Skills        []string               `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_base_models_base_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_base_models_base_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_base_models_base_models_proto_rawDescGZIP(), []int{1}
}

func (x *UserSettings) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserSettings) GetCpf() string {
	if x != nil {
		return x.Cpf
	}
	return ""
}

func (x *UserSettings) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UserSettings) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *UserSettings) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ChatId         string                 `protobuf:"bytes,2,opt,name=chatId,proto3" json:"chatId,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	MessageContent string                 `protobuf:"bytes,4,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_base_models_base_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_base_models_base_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_base_models_base_models_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	User1         *User                  `protobuf:"bytes,2,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         *User                  `protobuf:"bytes,3,opt,name=user2,proto3" json:"user2,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_base_models_base_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_base_models_base_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_base_models_base_models_proto_rawDescGZIP(), []int{3}
}

func (x *Chat) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Chat) GetUser1() *User {
	if x != nil {
		return x.User1
	}
	return nil
}

func (x *Chat) GetUser2() *User {
	if x != nil {
		return x.User2
	}
	return nil
}

func (x *Chat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Chat) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type Project struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ProjectId               string                 `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	ClientId                string                 `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	FreelancerId            string                 `protobuf:"bytes,3,opt,name=freelancerId,proto3" json:"freelancerId,omitempty"`
	Name                    string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description             string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Category                string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ProjectDeliveryDeadline string                 `protobuf:"bytes,7,opt,name=projectDeliveryDeadline,proto3" json:"projectDeliveryDeadline,omitempty"`
	Amount                  float32                `protobuf:"fixed32,8,opt,name=amount,proto3" json:"amount,omitempty"`
	RemainingTime           string                 `protobuf:"bytes,9,opt,name=remainingTime,proto3" json:"remainingTime,omitempty"`
	ClientName              string                 `protobuf:"bytes,10,opt,name=clientName,proto3" json:"clientName,omitempty"`
	FreelancerName          string                 `protobuf:"bytes,11,opt,name=freelancerName,proto3" json:"freelancerName,omitempty"`
	UrlImageProject         string                 `protobuf:"bytes,12,opt,name=urlImageProject,proto3" json:"urlImageProject,omitempty"`
	Status                  string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt               string                 `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CreatedBy               string                 `protobuf:"bytes,15,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedAt               string                 `protobuf:"bytes,16,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_base_models_base_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_base_models_base_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_base_models_base_models_proto_rawDescGZIP(), []int{4}
}

func (x *Project) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Project) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Project) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Project) GetProjectDeliveryDeadline() string {
	if x != nil {
		return x.ProjectDeliveryDeadline
	}
	return ""
}

func (x *Project) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Project) GetRemainingTime() string {
	if x != nil {
		return x.RemainingTime
	}
	return ""
}

func (x *Project) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Project) GetFreelancerName() string {
	if x != nil {
		return x.FreelancerName
	}
	return ""
}

func (x *Project) GetUrlImageProject() string {
	if x != nil {
		return x.UrlImageProject
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Project) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notificationId,proto3" json:"notificationId,omitempty"`
	SenderId       string                 `protobuf:"bytes,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,3,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	SenderName     string                 `protobuf:"bytes,7,opt,name=senderName,proto3" json:"senderName,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_base_models_base_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_base_models_base_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_base_models_base_models_proto_rawDescGZIP(), []int{5}
}

func (x *Notification) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Notification) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Notification) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_base_models_base_models_proto protoreflect.FileDescriptor

const file_base_models_base_models_proto_rawDesc = "" +
	"\n" +
	"\x1dbase_models/base_models.proto\x12\vbase_models\"\x9b\x01\n" +
	"\x04User\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x125\n" +
	"\bsettings\x18\x04 \x01(\v2\x19.base_models.UserSettingsR\bsettings\x12\x1a\n" +
	"\bPassword\x18\x05 \x01(\tR\bPassword\"\x8e\x01\n" +
	"\fUserSettings\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x10\n" +
	"\x03cpf\x18\x02 \x01(\tR\x03cpf\x12 \n" +
	"\vdateOfBirth\x18\x03 \x01(\tR\vdateOfBirth\x12\x1c\n" +
	"\tbiography\x18\x04 \x01(\tR\tbiography\x12\x16\n" +
	"\x06skills\x18\x05 \x03(\tR\x06skills\"\xa1\x01\n" +
	"\aMessage\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06chatId\x18\x02 \x01(\tR\x06chatId\x12\x1a\n" +
	"\bsenderId\x18\x03 \x01(\tR\bsenderId\x12&\n" +
	"\x0emessageContent\x18\x04 \x01(\tR\x0emessageContent\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\"\xac\x01\n" +
	"\x04Chat\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\x12'\n" +
	"\x05user1\x18\x02 \x01(\v2\x11.base_models.UserR\x05user1\x12'\n" +
	"\x05user2\x18\x03 \x01(\v2\x11.base_models.UserR\x05user2\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tcreatedBy\x18\x05 \x01(\tR\tcreatedBy\"\x95\x04\n" +
	"\aProject\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\tR\tprojectId\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\tR\bclientId\x12\"\n" +
	"\ffreelancerId\x18\x03 \x01(\tR\ffreelancerId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x128\n" +
	"\x17projectDeliveryDeadline\x18\a \x01(\tR\x17projectDeliveryDeadline\x12\x16\n" +
	"\x06amount\x18\b \x01(\x02R\x06amount\x12$\n" +
	"\rremainingTime\x18\t \x01(\tR\rremainingTime\x12\x1e\n" +
	"\n" +
	"clientName\x18\n" +
	" \x01(\tR\n" +
	"clientName\x12&\n" +
	"\x0efreelancerName\x18\v \x01(\tR\x0efreelancerName\x12(\n" +
	"\x0furlImageProject\x18\f \x01(\tR\x0furlImageProject\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\x0e \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tcreatedBy\x18\x0f \x01(\tR\tcreatedBy\x12\x1c\n" +
	"\tupdatedAt\x18\x10 \x01(\tR\tupdatedAt\"\xf4\x01\n" +
	"\fNotification\x12&\n" +
	"\x0enotificationId\x18\x01 \x01(\tR\x0enotificationId\x12\x1a\n" +
	"\bsenderId\x18\x02 \x01(\tR\bsenderId\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x03 \x01(\tR\n" +
	"receiverId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"senderName\x18\a \x01(\tR\n" +
	"senderName\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\tR\tcreatedAtB<Z:github.com/relaunch-cot/lib-relaunch-cot/proto/base_modelsb\x06proto3"

var (
	file_base_models_base_models_proto_rawDescOnce sync.Once
	file_base_models_base_models_proto_rawDescData []byte
)

func file_base_models_base_models_proto_rawDescGZIP() []byte {
	file_base_models_base_models_proto_rawDescOnce.Do(func() {
		file_base_models_base_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_models_base_models_proto_rawDesc), len(file_base_models_base_models_proto_rawDesc)))
	})
	return file_base_models_base_models_proto_rawDescData
}

var file_base_models_base_models_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_base_models_base_models_proto_goTypes = []any{
	(*User)(nil),         // 0: base_models.User
	(*UserSettings)(nil), // 1: base_models.UserSettings
	(*Message)(nil),      // 2: base_models.Message
	(*Chat)(nil),         // 3: base_models.Chat
	(*Project)(nil),      // 4: base_models.Project
	(*Notification)(nil), // 5: base_models.Notification
}
var file_base_models_base_models_proto_depIdxs = []int32{
	1, // 0: base_models.User.settings:type_name -> base_models.UserSettings
	0, // 1: base_models.Chat.user1:type_name -> base_models.User
	0, // 2: base_models.Chat.user2:type_name -> base_models.User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_base_models_base_models_proto_init() }
func file_base_models_base_models_proto_init() {
	if File_base_models_base_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_models_base_models_proto_rawDesc), len(file_base_models_base_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_models_base_models_proto_goTypes,
		DependencyIndexes: file_base_models_base_models_proto_depIdxs,
		MessageInfos:      file_base_models_base_models_proto_msgTypes,
	}.Build()
	File_base_models_base_models_proto = out.File
	file_base_models_base_models_proto_goTypes = nil
	file_base_models_base_models_proto_depIdxs = nil
}
